spring:
  application:
    name: api-gateway
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://54.211.114.211:8088/
          predicates:
            - Path=/auth-service/**

        - id: hotel-service
          uri: http://3.84.168.202:8083/
          predicates: Path=/hotel-service/**
          filters:
            - AuthenticationFilter

        - id: room-service
          uri: http://3.90.84.171:8084/
          predicates: Path=/room-service/**
          filters:
            - AuthenticationFilter

        - id: booking-service
          uri: http://100.24.255.65:8086/
          predicates: Path=/booking-service/**
          filters:
            - AuthenticationFilter

        - id: search-service
          uri: http://54.197.131.228:8090/
          predicates: Path=/search-service/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://174.129.84.80:8761/eureka

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
    com.hilltop: ${LOG_LEVEL:DEBUG}
  file:
      path: ${LOGPATH:/home/ubuntu/log}