spring:
  application:
    name: api-gateway
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://54.163.60.146:8088/
          predicates: Path=/auth-service/**

        - id: hotel-service
          uri: http://100.25.163.143:8083/
          predicates: Path=/hotel-service/**
          filters:
            - AuthenticationFilter

        - id: room-service
          uri: http://35.153.79.104:8084/
          predicates: Path=/room-service/**
          filters:
            - AuthenticationFilter

        - id: booking-service
          uri: http://54.160.111.224:8086/
          predicates: Path=/booking-service/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://100.26.231.196:8761/eureka

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
    com.hilltop: ${LOG_LEVEL:DEBUG}
  file:
      path: ${LOGPATH:/home/ubuntu/log}